# Generated by Django 3.2.7 on 2023-08-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=127)),
                ('year', models.DateField()),
                ('color', models.CharField(max_length=127)),
                ('horse_power', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
