# Generated by Django 3.2.7 on 2023-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=254)),
                ('last_name', models.CharField(max_length=127)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Default', 'Default')], max_length=127)),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машину', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=127, verbose_name='Цвет авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.PositiveIntegerField(default=0, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.CharField(max_length=127, verbose_name='Mарка авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
    ]
